title: The DayDreamer's Blog
description: 설명이 필요하나요
social_link: 'https://twitter.com/StationToStati6'
social_username: ''
github_repo: oddpennine
github_username: oddpennine
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /enigma_of_the_elysium
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow

theme: jekyll-theme-minimal